/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect,useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'



export default function Model({ ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/zzz.glb')
  const { actions } = useAnimations(animations, group)
  console.log('re-reder')
  
  const [colorFace,setColorFace] = useState('#ffffff')
  const [isVisibleGlass,setisVisibleGlass] = useState(true)


  useEffect(() => {
  
   window.addEventListener("colorFace",handleColorFace)
    return ()=>{
      console.log('unmound');
      window.removeEventListener('colorFace',handleColorFace)
  }

  }, [colorFace])

  useEffect(() => {
    actions.hello.play()
    window.addEventListener("onOffGlass",handleIsVisibleGlass)
     return ()=>{
       console.log('unmound');
       window.removeEventListener('onOffGlass',handleIsVisibleGlass)
   }
 
   }, [isVisibleGlass])
   function handleIsVisibleGlass(){
    console.log(isVisibleGlass)
    setisVisibleGlass( !isVisibleGlass);
  }

  function handleColorFace(){
    console.log(colorFace)
   
    setColorFace( (colorFace=='#fff222')?'#ffffff':'#fff222');
  }

  return (
 
 <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
        <primitive object={nodes.mixamorigHips} 
        
       
        
        />
        
        <skinnedMesh
       
          geometry={nodes._Boo_BigBoo_Big.geometry}
          material={materials['blinn6.001']}
          skeleton={nodes._Boo_BigBoo_Big.skeleton}
          material-color={colorFace} 
        />
        <skinnedMesh
       
          geometry={nodes._Boo_BootBoo_Big.geometry}
          material={materials['lambert16.002']}
          skeleton={nodes._Boo_BootBoo_Big.skeleton}
        />
        <skinnedMesh
          
          geometry={nodes._full_body.geometry}
          material={materials['blinn8.001']}
          skeleton={nodes._full_body.skeleton}
        />
        <skinnedMesh
        visible={isVisibleGlass}
          geometry={nodes._kinh.geometry}
          material={materials['blinn3.002']}
          skeleton={nodes._kinh.skeleton}
        />
        <skinnedMesh
          geometry={nodes._pCube4.geometry}
          material={materials['blinn4.002']}
          skeleton={nodes._pCube4.skeleton}
        />
    
      </group>
    </group>
    

   
  )
}


useGLTF.preload('/zzz.glb')
